### ISSUE TITLE
[lit-html] Sauce testing on Safari routinely flaky with `testsStartTimeout` error

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-html#1550]
# Description
Safari 13 often fails on CI (Sauce) with the following error (flaky):

```
Browser tests did not start after 120000ms You can increase this timeout with the testsStartTimeout option. Check the browser logs or open the browser in debug mode for more information.
```

Initial debugging indicates it is a failure that occurs when `startSession()` (called from `@web/test-runner-mocha/dist/standalone.js`) in an `html` test is not acknowledged by the test runner.

## Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari 13
- [ ] Safari 10
- [ ] IE 11

**Comment by kevinpschaaf** [comment]
We've tried several updates to the modern-web tools to try and address this, but some lingering timeouts remain. For now we've separated IE testing into its own sauce job, to at least consolidate the flaky tests there. Putting this back in the backlog since there's not a clear next step.

**Comment by bicknellr** [comment]
We now have at least one non-timeout IE11 failure which typically looks like this:
```
@lit-labs/scoped-registry-mixin:  ❌ scoped-registry-mixin > host element should apply static styles
@lit-labs/scoped-registry-mixin:       AssertionError: expected 'rgb(0, 0, 0)' to equal 'rgb(255, 0, 0)'
@lit-labs/scoped-registry-mixin:       + expected - actual
@lit-labs/scoped-registry-mixin:       
@lit-labs/scoped-registry-mixin:       -rgb(0, 0, 0)
@lit-labs/scoped-registry-mixin:       +rgb(255, 0, 0)
@lit-labs/scoped-registry-mixin:       
@lit-labs/scoped-registry-mixin:       at r (../labs/scoped-registry-mixin/node_modules/@esm-bundle/chai/esm/chai.js:2275:17)
@lit-labs/scoped-registry-mixin:       at i.prototype.assert (../labs/scoped-registry-mixin/node_modules/@esm-bundle/chai/esm/chai.js:225:19)
@lit-labs/scoped-registry-mixin:       at r.equal (../labs/scoped-registry-mixin/node_modules/@esm-bundle/chai/esm/chai.js:879:17)
@lit-labs/scoped-registry-mixin:       at _callee5$ (../labs/scoped-registry-mixin/development/test/scoped-registry-mixin_test.js:223:19)
@lit-labs/scoped-registry-mixin:       at tryCatch (../polyfills/regenerator-runtime.de2e6a3a74a500cae72a3cab1a403efc.js:63:7)
@lit-labs/scoped-registry-mixin:       at invoke (../polyfills/regenerator-runtime.de2e6a3a74a500cae72a3cab1a403efc.js:294:9)
@lit-labs/scoped-registry-mixin:       at Anonymous function (../polyfills/regenerator-runtime.de2e6a3a74a500cae72a3cab1a403efc.js:119:9)
@lit-labs/scoped-registry-mixin:       at asyncGeneratorStep (../labs/scoped-registry-mixin/development/test/scoped-registry-mixin_test.js:6:86)
@lit-labs/scoped-registry-mixin:       at _next (../labs/scoped-registry-mixin/development/test/scoped-registry-mixin_test.js:8:196)
```
It seems like it's also flaky; here are some recent runs (earliest to latest, not consecutive):
- https://github.com/lit/lit/runs/3657226734 - has this failure
- https://github.com/lit/lit/runs/3658141368 - does not have this failure
- https://github.com/lit/lit/runs/3694002328 - has this failure
- https://github.com/lit/lit/runs/3694145267 - does not have this failure
