### ISSUE TITLE
[lit-next] @lit-labs/scoped-registry-mixin incompatible with @open-wc/testing

### ISSUE THREAD

**Issue by sync** [Polymer/lit-html#1730]
# Description
@lit-labs/scoped-registry-mixin incompatible with @open-wc/testing

# Lit versions
2.0.0-pre.2

# Steps to Reproduce

1. Write this code...

```
import {LitElement, html} from 'lit';
import {ScopedRegistryHost} from '@lit-labs/scoped-registry-mixin';

import {SimpleGreeting} from './simple-greeting.js';

class ScopedComponent extends ScopedRegistryHost(LitElement) {
  // Elements here will be registered against the tag names provided only
  // in the shadow root for this element
  static elementDefinitions = {
    'simple-greeting': SimpleGreeting,
  };

  render() {
    return html` <simple-greeting
      id="greeting"
      name="scoped world"
    ></simple-greeting>`;
  }
}
```

and write a test for it and you'll end up with an error

## Expected Results
No error

## Actual Results (
```
MonoAlertComp > passes the a11y audit
      Error: Uncaught TypeError: Illegal constructor (http://localhost:8000/__wds-outside-root__/2/node_modules/@lit-labs/scoped-registry-mixin/scoped-registry-mixin/scoped-registry-mixin.js:15)
        at NodePart.__insert (../../node_modules/lit-html/src/lib/parts.ts:257:3)
        at NodePart.__commitNode (../../node_modules/lit-html/src/lib/parts.ts:265:9)
        at NodePart.__commitTemplateResult (../../node_modules/lit-html/src/lib/parts.ts:302:11)
        at NodePart.commit (../../node_modules/lit-html/src/lib/parts.ts:242:5)
        at render (../../node_modules/lit-html/src/lib/render.ts:52:6)
        at litFixtureSync (../../node_modules/@open-wc/testing-helpers/src/litFixture.js:42:3)
        at litFixture (../../node_modules/@open-wc/testing-helpers/src/litFixture.js:67:14)
        at fixture (../../node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:62:12)
        at o.<anonymous> (src/MonoAlertComp.test.ts:44:21)
```

## Browsers Affected

- [x] Chrome

**Comment by sync** [comment]
let me know if you need a reproduction link :-)

**Comment by justinfagnani** [comment]
Seems like this issue belongs in https://github.com/open-wc/open-wc

cc @manolakis @LarsDenBakker and @daKmoR
